services:
  # Network Monitor Application
  netmon2:
    container_name: netmon2
    image: matjazt/netmon2:1.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/log/netmon2:/app/log
    restart: unless-stopped
