services:
  # Network Monitor Application
  netmon2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netmon2
    environment:
      - TZ=Europe/Ljubljana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./log:/app/log
    restart: unless-stopped
